###
### Create a new user
###
POST {{protocol}}{{host}}:{{port}}/auth
Content-Type: application/json
Accept: application/json

{
  "username": "user1",
  "password": "mypassword",
  "email": "user1@gameveilingen.nl"
}

###
### Attempt to create a user with missing email
###

POST {{protocol}}{{host}}:{{port}}/auth
Content-Type: application/json
Accept: application/json

{
  "username": "user1",
  "password": "mypassword"
}

###
### Attempt to create a user with an existing email
###

POST {{protocol}}{{host}}:{{port}}/auth
Content-Type: application/json
Accept: application/json

{
  "username": "user2",
  "password": "mypassword",
  "email": "user@gameveilingen.nl"
}

###
### Attempt to create a user with an existing username
###

POST {{protocol}}{{host}}:{{port}}/auth
Content-Type: application/json
Accept: application/json

{
  "username": "user",
  "password": "mypassword123",
  "email": "user2@gameveilingen.nl"
}

###
### Attempt to create a user with a password that is too short
###

POST {{protocol}}{{host}}:{{port}}/auth
Content-Type: application/json
Accept: application/json

{
  "username": "user3",
  "password": "short",
  "email": "user3@gameveilingen.nl"
}