###
### Login a user and store the token
###
POST {{protocol}}{{host}}:{{port}}/tokens
Content-Type: application/json
Accept: application/json

{
  "password": "mypassword",
  "email": "user1@gameveilingen.nl"
}

> {%
    client.global.set("token", response.body.token);
%}

###
### Try to login with wrong password
###
POST {{protocol}}{{host}}:{{port}}/tokens
Content-Type: application/json
Accept: application/json

{
  "password": "wrongpassword",
  "email": "user1@gameveilingen.nl"
}

###
### Attempt to login without an email (missing field)
###

POST {{protocol}}{{host}}:{{port}}/tokens
Content-Type: application/json
Accept: application/json

{
  "password": "mypassword"
}